version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "88:80/tcp"
    environment:
      - "TZ=America/Chicago"
      - "WEBPASSWORD=${PIHOLE_PASSWORD}"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  nginx:
    container_name: nginx
    ports:
      - "32400:32400"
      - "8096:8096"
    volumes:
      - ''
  plex:
    container_name: plex
    image: pass

  noip:
    image: uping/no-ip
    container_name: noip
    restart: unless-stopped
    environment:
      - "USERNAME=${USERNAME}"
      - "PASSWORD=${PASSWORD}"
      - "DOMAINS=${DOMAIN1}"
      - "INTERVAL=${INTERVAL}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/config:/config